// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_wholl_pollinate_the_crops_now = "CgkInJX8ptwQEAIQIw"; // <GPGSID>
        public const string achievement_bringin_in_the_heat = "CgkInJX8ptwQEAIQBw"; // <GPGSID>
        public const string achievement_i_fier_nothing = "CgkInJX8ptwQEAIQCw"; // <GPGSID>
        public const string achievement_still_going_strong = "CgkInJX8ptwQEAIQIQ"; // <GPGSID>
        public const string achievement_a_psyth_to_behold = "CgkInJX8ptwQEAIQJw"; // <GPGSID>
        public const string achievement_buzzer_round = "CgkInJX8ptwQEAIQCA"; // <GPGSID>
        public const string achievement_runners_high = "CgkInJX8ptwQEAIQFg"; // <GPGSID>
        public const string achievement_brown_hawk_down = "CgkInJX8ptwQEAIQHg"; // <GPGSID>
        public const string achievement_razed_to_the_ground = "CgkInJX8ptwQEAIQGg"; // <GPGSID>
        public const string achievement_ice_ice_baby = "CgkInJX8ptwQEAIQBg"; // <GPGSID>
        public const string achievement_not_safe_ever_under_armor = "CgkInJX8ptwQEAIQHw"; // <GPGSID>
        public const string achievement_pest_control = "CgkInJX8ptwQEAIQIA"; // <GPGSID>
        public const string leaderboard_distance = "CgkInJX8ptwQEAIQAw"; // <GPGSID>
        public const string achievement_icy_hot = "CgkInJX8ptwQEAIQDg"; // <GPGSID>
        public const string achievement_felina = "CgkInJX8ptwQEAIQLA"; // <GPGSID>
        public const string achievement_i_see_fire_now_i_dont = "CgkInJX8ptwQEAIQJg"; // <GPGSID>
        public const string achievement_bee_gone = "CgkInJX8ptwQEAIQFQ"; // <GPGSID>
        public const string achievement_tonight_we_ride = "CgkInJX8ptwQEAIQEA"; // <GPGSID>
        public const string achievement_mass_murderer = "CgkInJX8ptwQEAIQHA"; // <GPGSID>
        public const string achievement_earth_quakes_no_more = "CgkInJX8ptwQEAIQHQ"; // <GPGSID>
        public const string achievement_paranormal_inactivity = "CgkInJX8ptwQEAIQGQ"; // <GPGSID>
        public const string achievement_genocidal = "CgkInJX8ptwQEAIQKg"; // <GPGSID>
        public const string achievement_baby_steps = "CgkInJX8ptwQEAIQCQ"; // <GPGSID>
        public const string achievement_pins_drop_and_silence = "CgkInJX8ptwQEAIQEg"; // <GPGSID>
        public const string achievement_el_torero = "CgkInJX8ptwQEAIQKw"; // <GPGSID>
        public const string leaderboard_kills = "CgkInJX8ptwQEAIQAg"; // <GPGSID>
        public const string achievement_owin__runners_die_twice = "CgkInJX8ptwQEAIQIg"; // <GPGSID>
        public const string achievement_birdwatching_isnt_my_thing = "CgkInJX8ptwQEAIQEQ"; // <GPGSID>
        public const string achievement_blink_n_didnt_miss = "CgkInJX8ptwQEAIQCg"; // <GPGSID>
        public const string achievement_its_over_9000 = "CgkInJX8ptwQEAIQLw"; // <GPGSID>
        public const string achievement_icykilled = "CgkInJX8ptwQEAIQKQ"; // <GPGSID>
        public const string achievement_debugging_complete = "CgkInJX8ptwQEAIQLg"; // <GPGSID>
        public const string achievement_youre_a_wizrd = "CgkInJX8ptwQEAIQBQ"; // <GPGSID>
        public const string achievement_no_resurrections_this_time = "CgkInJX8ptwQEAIQKA"; // <GPGSID>
        public const string achievement_they_see_me_rollin = "CgkInJX8ptwQEAIQFA"; // <GPGSID>
        public const string achievement_ski_and_destroy = "CgkInJX8ptwQEAIQGw"; // <GPGSID>
        public const string achievement_lit_af = "CgkInJX8ptwQEAIQGA"; // <GPGSID>
        public const string achievement_death_comes_in_all_lanes = "CgkInJX8ptwQEAIQEw"; // <GPGSID>
        public const string achievement_ghostbusted = "CgkInJX8ptwQEAIQDA"; // <GPGSID>
        public const string leaderboard_score = "CgkInJX8ptwQEAIQAQ"; // <GPGSID>
        public const string achievement_peak_athleticism = "CgkInJX8ptwQEAIQJA"; // <GPGSID>
        public const string achievement_serial_killer = "CgkInJX8ptwQEAIQDw"; // <GPGSID>
        public const string achievement_an_eye_for_an_eye = "CgkInJX8ptwQEAIQFw"; // <GPGSID>
        public const string achievement_goodbye_darkness_my_old_friend = "CgkInJX8ptwQEAIQJQ"; // <GPGSID>
        public const string achievement_spearheading_its_way_to_extinction = "CgkInJX8ptwQEAIQLQ"; // <GPGSID>
        public const string achievement_razer_sharp = "CgkInJX8ptwQEAIQDQ"; // <GPGSID>

}

